### ISSUE TITLE
Prod transitions between section mode and cluster mode are very unreliable for some presentations

### ISSUE THREAD

**Issue by oserban** [dsi-icl/gdo-loader#16]
I noticed this morning while fixing something else with @davidbirchwork that switching between:

- DSI Intro (section mode) <-> Bitcoin (cluster mode) is not working. 
- tested other random cluster mode presentation to section mode and it works if the section mode presentation is not DSI intro and a few others. For the first issue, the section mode presentation can be anything as long as the second presentation is bitcoin.

The screens seem to be stuck in in section mode, while the content is loaded in cluster mode. Ghost btn does not fix the issue and you need to switch screens manually to display the content.

**Comment by miguems** [comment]
Hi @oserban , Bitcoin in cluster mode?

**Comment by oserban** [comment]
Yes. Bitcoin in cluster mode. It's called **Bitcoin history** on the control panel. Everything was run through the OVE, with dsiav for screen management.

**Comment by senakafdo** [comment]
@miguems - This is **not a bug**. I tested this with @oserban and @davidbirchwork and we concluded that the behaviour is down to DSI-AV not switching screens before a specific timeout after completing the operation.
